### ISSUE TITLE
各種エラーハンドリング用メッセージ定義の末尾の\nは削除

### ISSUE THREAD

**Issue by y-naga** [sheepdog/cinder#47]
各種エラーハンドリング用メッセージ定義の末尾の\nは削除する。
- except内のstderrは以下で改行除いて取得してendswithで比較
  stderr = e.kwargs['stderr'].rstrip('\n')
- コマンド正常時の戻りで確認する場合はで比較
  stderr.rstrip().endswith(self.DOG_RESP_VDI_NOT_FOUND):

必要なところは統一

> DOG_RESP_VDI_NOT_FOUND_SUCCESS = ': No VDI found\n'
> DOG_RESP_VDI_NOT_FOUND_BY_EXCEPTION = ': No VDI found\n'
> ↓統一
> DOG_RESP_VDI_NOT_FOUND = ': No VDI found'

**Comment by saeki-masaki** [comment]
エラーメッセージの判定は、startswith / endswith / in が混用されている
 in を利用した判定に統一したほうがよい。

**Comment by tishizaki** [comment]
コミュニティからのコメントがあったため、メッセージ定義の"\n"の類はsheepdog-devel, コミュニティ投稿用のものは排除済みです。
endswithで対応していた部分をrstrip()を使うように変更してます
