### ISSUE TITLE
不要テストデータの整理

### ISSUE THREAD

**Issue by y-naga** [sheepdog/cinder#49]
テストのテスト用データ構造のうち、TEST_VOLUME, TEST_CLONED_VOLUMEのvolume_nameは不要.
最終的には削除する対象.

**Comment by tishizaki** [comment]
dictからobjectへ変更した際に排除しました. sheepdog-devel, 投稿した版へも反映済.
また、nameはfake_volumeを使ってvolumeオブジェクトを生成すると、volume-<id> の形式で返すような仕様になっているため、オブジェクト生成する元データの TEST_VOL_DATA, TEST_CLONED_VOL_DATAからはnameを排除してます.
